const imgBase = "https://raw.githubusercontent.com/neyakkoot/MiLifeStyle_Products_Details_Prize/main/MiLifeStyle_Products_Pictures/";

const products = [
/* HEALTH CARE (ஆரோக்கிய பராமரிப்பு) */
{cat:"HC",name:"ELEMENTS CYCLOVA 30 CAPSULES",r:1650,m:2200,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS ANTILERGY LIQUID 200ML",r:308,m:385,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS THYHEALTH LIQUID 200ML",r:594,m:770,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS AYUSHWAAS AVALEHA 250GMS",r:1067,m:1430,img:"Ayushwaas%20avaleha.jpg"},
{cat:"HC",name:"ELEMENTS NATCIUM",r:935,m:1375,img:"Antilersy.jpg"},
{cat:"HC",name:"ON & ON DIABA LIFE 600.85 MG",r:2200,m:2750,img:"Antilersy.jpg"},
{cat:"HC",name:"ON & ON KAVCH PRASH",r:979,m:1424,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS LIV AGAIN LIQUID",r:198,m:264,img:"Blood%20Purifier.jpg"},
{cat:"HC",name:"ELEMENTS COF NIL",r:154,m:214,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS WOMAN COMP",r:275,m:374,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS M.G. BLD PRF",r:308,m:418,img:"Blood%20Purifier.jpg"},
{cat:"HC",name:"ELEMENTS MAN SHKTIMN",r:1089,m:1375,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS WELL HART",r:594,m:797,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS BELOW 37",r:748,m:1001,img:"Below%2037.jpg"},
{cat:"HC",name:"ON & ON MOROLIFE",r:2750,m:3300,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS WELLNESS PROBIOTIC",r:688,m:825,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS URI FLUSH 3 LIQUID",r:374,m:522,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS NO VEDNA CAP",r:1012,m:1265,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS NO VEDNA GEL",r:253,m:319,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS PHYT STRS CP",r:825,m:1122,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS IMMUNO + CAP",r:825,m:1034,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS LIV AGAIN C",r:792,m:990,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS DAILY DETOX",r:792,m:990,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS WND HLNG CRM",r:143,m:214,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS WELLNESS AYUHEEL 50GMS",r:193,m:242,img:"AyuHeel.jpg"},
{cat:"HC",name:"ELEMENTS WELLNESS PRO NASIKA 20ML",r:187,m:242,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS WELLNESS EYE NERGY 10ML",r:165,m:209,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS PROTEIN PWDR",r:2420,m:3080,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS FEALING IRON CAPSULE",r:627,m:852,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS URI FLUSH-3 PLUS TABLETS",r:902,m:1210,img:"Antilersy.jpg"},
{cat:"HC",name:"ELEMENTS FEALING IRON SYRUP",r:314,m:418,img:"Antilersy.jpg"},

/* PERSONAL CARE (தனிநபர் பராமரிப்பு) */
{cat:"PC",name:"ON & ON BDY BTR CRM",r:231,m:330,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS CHAMPI CHMPN",r:429,m:577,img:"Bhringraj%20Hair%20Oil%20%26%20Complete%20Care%20Shampoo.jpg"},
{cat:"PC",name:"ELEMENTS CC SHAMPOO",r:275,m:374,img:"Bhringraj%20Hair%20Oil%20%26%20Complete%20Care%20Shampoo.jpg"},
{cat:"PC",name:"ELEMENTS A.D. SHAMPOO",r:275,m:374,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS MULTI-ACTION CREAM",r:275,m:374,img:"Antilersy.jpg"},
{cat:"PC",name:"ON & ON SANDALWOOD SOAP 75G",r:83,m:108,img:"Antilersy.jpg"},
{cat:"PC",name:"ON & ON PAPAYA SOAP 75G",r:83,m:108,img:"Antilersy.jpg"},
{cat:"PC",name:"ON & ON NEEM SOAP 75G",r:83,m:108,img:"Antilersy.jpg"},
{cat:"PC",name:"ON & ON TURMERIC SOAP 75G",r:83,m:108,img:"Antilersy.jpg"},
{cat:"PC",name:"ON & ON MILK & STRAWBERRY SOAP",r:83,m:108,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS RADIANT GLOW FACE WASH",r:187,m:258,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS WHITENING BODY LOTION",r:165,m:220,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS COCOA BUTTER LOTION",r:193,m:264,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS ALOE VERA LOTION",r:209,m:286,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS EMOLLIENT BODY CREAM",r:209,m:286,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS ROSE HAND WASH",r:330,m:440,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS 3 IN 1 FACE WASH",r:149,m:198,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS UNDER EYE GEL",r:237,m:297,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS ACTI-FRESH SHAVE GEL",r:242,m:308,img:"Acti-Fresh%20Shave%20Gel.jpg"},
{cat:"PC",name:"ELEMENTS 8 IN 1 HAIR CONDITIONER",r:358,m:451,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS PRIVY WASH 100ML",r:286,m:363,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS EGA DAY CREAM",r:534,m:671,img:"12-in-1%20Day%20Protection%20Cream.jpg"},
{cat:"PC",name:"ELEMENTS EGA NIGHT CREAM",r:534,m:671,img:"12-in-1%20Night%20Repair%20Cream.jpg"},
{cat:"PC",name:"ON & ON BHRNGRAJ OIL",r:358,m:484,img:"Bhringraj%20Hair%20Oil%20%26%20Complete%20Care%20Shampoo.jpg"},
{cat:"PC",name:"ON & ON HRB. T-PST",r:143,m:194,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS RED HRBL TOOTH PASTE",r:160,m:205,img:"Antilersy.jpg"},
{cat:"PC",name:"ELEMENTS F G TOOTH PASTE",r:165,m:226,img:"Antilersy.jpg"},
{cat:"PC",name:"ON & ON COLOUR SHAMPOO",r:83,m:110,img:"Antilersy.jpg"},
{cat:"PC",name:"ON & ON HERBAL ROLLON INHALER",r:138,m:192,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR NU FEMME PERFUME",r:550,m:1100,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR TYZON PERFUME",r:550,m:1100,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR NU FEMME DEO",r:182,m:231,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR TYZON DEO",r:182,m:231,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR TOOTH BRUSH PACK OF 4",r:105,m:126,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR NEEM FACE WASH",r:121,m:154,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR PAPAYA FACE WASH",r:121,m:154,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR WALLNUT SCRUB",r:138,m:176,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR PETROLEUM JELLY",r:50,m:66,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR SHAMPOO TUBE",r:24,m:38,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR AMLA HAIR OIL",r:149,m:187,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR TULSI & MINT PASTE",r:61,m:75,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR NEEM & TULSI SOAP",r:39,m:54,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR LIME & ALOE SOAP",r:39,m:54,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR ROSE FRAGRANCE SOAP",r:39,m:54,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR JASMINE SOAP",r:39,m:54,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR ANTIBACTERIAL SOAP",r:39,m:54,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR SANDALWOOD SOAP",r:39,m:54,img:"Antilersy.jpg"},
{cat:"PC",name:"NEUSTAR TALC POWDER",r:154,m:198,img:"Antilersy.jpg"},

/* FOOD & BEVERAGE (உணவு மற்றும் பானங்கள்) */
{cat:"FB",name:"ON & ON 9 E 5 HEALTH DRINK",r:3245,m:4070,img:"Antilersy.jpg"},
{cat:"FB",name:"ON & ON SPRLN GOLD",r:1320,m:1650,img:"Antilersy.jpg"},
{cat:"FB",name:"ON & ON MASALA KAWAH TEA",r:165,m:209,img:"Antilersy.jpg"},
{cat:"FB",name:"ON & ON KASHMIRI KAWAH TEA",r:330,m:418,img:"Antilersy.jpg"},
{cat:"FB",name:"ON & ON NU WOMAN NAPKINS",r:275,m:357,img:"Antilersy.jpg"},
{cat:"FB",name:"ON & ON NUTRILIFE CHOCOLATE",r:2090,m:2640,img:"Antilersy.jpg"},
{cat:"FB",name:"AAHAR TEALITE",r:330,m:420,img:"Antilersy.jpg"},

/* HOME CARE (வீட்டு பராமரிப்பு) */
{cat:"HM",name:"ANTI BACTERIAL DISH WASH BAR",r:66,m:88,img:"Antilersy.jpg"},
{cat:"HM",name:"KILL & SHINE TOILET CLEANER",r:83,m:110,img:"Antilersy.jpg"},
{cat:"HM",name:"DISINFECTANT FLOOR CLEANER",r:99,m:132,img:"Antilersy.jpg"},
{cat:"HM",name:"CLEAN & SHINE DISH WASH LIQUID",r:127,m:165,img:"Antilersy.jpg"},
{cat:"HM",name:"MAX BRIGHT LAUNDRY DETERGENT",r:187,m:242,img:"Antilersy.jpg"},
{cat:"HM",name:"STREAK FREE GLASS CLEANER",r:77,m:93,img:"Antilersy.jpg"},

/* AGRO CARE (விவசாயம்) */
{cat:"AG",name:"INDIAGRO MI PROUD 250ML",r:1045,m:1320,img:"Antilersy.jpg"},
{cat:"AG",name:"INDIAGRO MI CITRA 250ML",r:1650,m:2062,img:"Antilersy.jpg"},
{cat:"AG",name:"INDIAGRO MI VEER 250ML",r:2310,m:2915,img:"Antilersy.jpg"},
{cat:"AG",name:"INDIAGRO BHUASTRA SUPER 2KG",r:1210,m:1512,img:"Antilersy.jpg"},
{cat:"AG",name:"INDIAGRO MI SPRAY PLUS 100ML",r:440,m:550,img:"Antilersy.jpg"},
{cat:"AG",name:"INDIAGRO GROWMAGIC ADVANCE",r:1419,m:1815,img:"Antilersy.jpg"},
{cat:"AG",name:"INDIAGRO MODIPHY 250ML",r:440,m:550,img:"Antilersy.jpg"},
{cat:"AG",name:"INDIAGRO Y-RAS PLUS 250ML",r:825,m:1045,img:"Antilersy.jpg"},
{cat:"AG",name:"INDIAGRO OLIF SUPER 16 500ML",r:1210,m:1430,img:"Antilersy.jpg"},
];
